### ISSUE TITLE
Option for self signed certificates

### ISSUE THREAD

**Issue by mjmj** [cyberark/conjur-api-go#42] opened 2019-01-23 06:26 UTC
I might be overlooking it, but is there an option or technique with this module to ignore certificate validation? I'm passing an api token but using a self signed cert and get the following error when trying to connect to our on prem conjur host, which is not public and I don't care to secure the connection at the moment. 

    panic: Get https://conjur.our-office.com/api/secrets/myaccount/variable/myvarname: x509: 
    certificate signed by unknown authority (possibly because of "x509: invalid signature: parent 
    certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate blah.amazonaws.com")

Thanks.

**Comment by sgnn7** [comment] 2019-01-23 15:04
Hey @mjmj!

We use self-signed certs with this API in many places so it should work fine (client setup code is [here](https://github.com/cyberark/conjur-api-go/blob/bb43c2b86d76e1028e6784a59c4579703eeb9922/conjurapi/client.go#L218-L227)) but you *must have the Conjur host's certificate (or CA cert) available to the API* using either the standard config file or [these](https://github.com/cyberark/conjur-api-go/blob/bb43c2b86d76e1028e6784a59c4579703eeb9922/conjurapi/config.go#L110-L111) environment variables. One of those variables is for the path to the cert and one is for the actual cert data - you don't need both as far as I know.

While it's understandable that you don't have a need for secure connection back to the Conjur host, allowing invalid host's certs to be a configurable setting would indirectly cause a reduction in security of our clients in the field so we feel very compelled not to implement such a feature. With that said, if you feel strongly about it, you can open a new feature request and we can gauge our user's need for this functionality from there.

I will close the issue as "can't reproduce" but feel free to comment/reopen if I misunderstood your problem description.

Thanks!

**Closed by sgnn7** 2019-01-23 15:04 UTC
Labels: component/api/go, kind/documentation, triage/not-reproducible

**Comment by mjmj** [comment] 2019-01-23 16:34
Thank you for taking the time to write such a detailed response, that was very helpful!
